[phases.setup]
nixPkgs = ['tesseract', 'python39', 'python39Packages.pip']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = [
  'pip3 install opencv-python-headless pytesseract numpy Pillow --no-cache-dir'
]

[start]
cmd = 'cd backend && npm start'
